---
name: Pull Request checks

"on":
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  terraform-fmt:
    name: Terraform Formatting
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
      - name: setup terraform
        uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36  # v3.0.0
      - name: terraform fmt
        run: terraform fmt -check -diff -recursive ./

  terraform-validate:
    name: Terraform config validation
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
      - name: setup terraform
        uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36  # v3.0.0
      - name: terraform init
        run: terraform init
      - name: terraform validate
        run: terraform validate

  tflint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
      - name: cache tflint
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84  # v3.3.2
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      - name: setup tflint
        uses: terraform-linters/setup-tflint@19a52fbac37dacb22a09518e4ef6ee234f2d4987  # v4.0.0
      - name: tflint init
        run: tflint --init
      - name: tflint validate
        run: tflint -f compact --module
